name: Lint (Black code style)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  black-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: psf/black@stable
        with:
          version: "26.5.1"
